[[language]]
name = "nu"
auto-format = true
formatter = { command = "topiary", args = ["format", "--language", "nu"] }
indent = { tab-width = 4, unit = "    " }
# soft-wrap = { enable = false }

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'prettier', args = [ "--parser", "markdown", "--prose-wrap", "never" ] }
auto-format = false
