[[verbs]]
invocation = "ok"
shortcut = "e"
execution = ":print_path"
leave_broot = true
from_shell = true
key = "enter"
apply_to = "file"

[[verbs]]
invocation = "ok"
execution = ":print_path"
leave_broot = true
key = "alt-enter"
apply_to = "any"

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
leave_broot = false
execution = "git difftool -y {file}"

[[verbs]]
invocation = "backup {version}"
key = "ctrl-b"
leave_broot = false
auto_exec = false
execution = "cp -r {file} {parent}/{file-stem}-{version}{file-dot-extension}"

[[verbs]]
key = "ctrl-shift-a"
execution = ":stage_all_files"

[[verbs]]
key = "F5"
external = "cp -r {file} {other-panel-directory}"
leave_broot = false

[[verbs]]
key = "F6"
external = "mv {file} {other-panel-directory}"
leave_broot = false

[[verbs]]
key = "ctrl-t"
execution = ":toggle_stage"
leave_broot = false

[[verbs]]
invocation = "vd"
shortcut = "vd"
apply_to = "file"
external = "vd {file}"
leave_broot = false

[[verbs]]
invocation = "pbcopy"
shortcut = "pb"
leave_broot = false
external = [
    "sh",
    "-c",
    "echo '{file-git-relative}' | pbcopy",
]

[[verbs]]
invocation = "pbfull"
shortcut = "pbf"
leave_broot = false
external = [
    "sh",
    "-c",
    "echo '{file}' | pbcopy",
]

[[verbs]]
invocation = "pbcopy"
shortcut = "pbq"
leave_broot = true
external = [
    "sh",
    "-c",
    "echo '{file-git-relative}' | pbcopy",
]

[[verbs]]
invocation = "pbfull"
shortcut = "pbfq"
leave_broot = true
external = [
    "sh",
    "-c",
    "echo '{file}' | pbcopy",
]
